### ISSUE TITLE
menu数量计算错误

### ISSUE THREAD

**Issue by iBCode** [jsfu/JSDropDownMenu#1]
非常感谢分享源代码，在使用过程中发现一个问题，在demo中修改代码使第三个menu是列表形式，而非collectionview格式，在显示“智能排序”menu时，直接切换到“不限人数”就会出现多余的空白空间，如下截图

![qq20150305-2 2x](https://cloud.githubusercontent.com/assets/7181827/6497912/c3c92664-c320-11e4-98ba-9388b6486492.png)

**Comment by jsfu** [comment]
你好，代码中默认的是最少显示5行高度，如果不需要这种方式，可以去掉默认最少行数

搜索如下方法
- (void)animateLeftTableView:(UITableView *)leftTableView rightTableView:(UITableView *)rightTableView show:(BOOL)show complete:(void(^)())complete

**Comment by iBCode** [comment]
嗯嗯，是的，谢谢。

还有一个问题，请问有一个update或者reload data source的接口吗？如果筛选分类是从后台获取的，获取可能会需要点时间和延迟，有可能在data source执行之后才返回，这时该如何重新加载data souce显示新的筛选数据？

**Comment by jsfu** [comment]
每次展开菜单时都会reload，详细代码可以看menuTapped:

**Comment by iBCode** [comment]
All right. Thank you. Have a great day.
