### ISSUE TITLE
这是我用过的最难用的框架，没有之一

### ISSUE THREAD

**Issue by SunOddman** [jsfu/JSDropDownMenu#11]
可读性、定制性，改也改不动，到处都在设置UI，记录选中的行不用个变量来保存，要通过对比Layer的字符串来判断，OMG，好蠢的做法

**Comment by jsfu** [comment]
数据源各种代理方法都提供给你了，本来就是要你自己使用时自己去保存的，另外源码都给你了，怎么可能修改不了
