### ISSUE TITLE
how to reloadData

### ISSUE THREAD

**Issue by bluesky0109** [jsfu/JSDropDownMenu#4]
所需的data从网络获取的，获取新数据后如何reloadData

**Comment by jsfu** [comment]
现在还没加reloadData功能，不过下拉菜单里面的数据是展开菜单时才去获取的，所以即使你是从网络上获取的也无所谓，只需要在展开时能在代理里获取到数据就可以。另外八卦一下，你的账号bluesky跟航信的bluesky有关系吗？

**Comment by bluesky0109** [comment]
bluesky跟航信的没有关系，自己很多其他账号的昵称用这个习惯了。另从网络上获取的也无所谓，只需要在展开时能在代理里获取到数据就可以，很多时候点击后网络请求的数据还没到，中间网络慢的话后面即使网络数据到了 由于没有reloaddata的接口 还是会显示空白的，建议还是考虑增加这种接口。
