### ISSUE TITLE
功能疑问

### ISSUE THREAD

**Issue by liaolongcheng** [jsfu/JSDropDownMenu#5]
jsfu 老师你好，我看到您的JSDropDownMenu菜单写的很好，可以实现大多数功能，可是我现在项目有一个需求，在左边需要显示一个列表，在右边需要一个collectionView 并且右边的collectionView需要有一个分组有header 那么这样的情况我想问问用您的控件可以实现么

**Comment by jsfu** [comment]
需要你自己去改源码才行
