### ISSUE TITLE
下拉的菜单的点击事件被下面的tableVIew截获

### ISSUE THREAD

**Issue by tangzzz-fan** [jsfu/JSDropDownMenu#6]
我在tableView的headerViewForSection上添加下拉菜单，我实现了数据源和代理方法，但是点击下拉菜单的选项时，选项没有反应，此时点击却被菜单下一层的tableView捕捉了，我在黑色蒙层上滑动，依然只能够对tableView操作，此时点击tableView的组头上的选项是有反应的。
同样，我在viewController的View中添加一个UIView放dropdownMenu,和另一个tableView，此时，菜单能正常弹出并进行交互。
能不能看一下？

**Comment by jsfu** [comment]
我猜是因为添加tableview是 [self.superview addSubview:leftTableView]，你在headerViewForSection里面添加确实是有问题的，超出了headerViewForSection显示的高度。你可以改一下源码，比如传一个足够显示菜单的view进去，让菜单显示在这个view上:)

**Comment by tangzzz-fan** [comment]
恩，是的，问题解决了，因为我在headerView中先创建了一个UIView，然后才把menu添加在headerView中，我直接初始化menu并返回给headerViewForSection，这样就行了。
