### ISSUE TITLE
当menu控件被添加在不同父视图上时，事件处理的疑惑

### ISSUE THREAD

**Issue by tangzzz-fan** [jsfu/JSDropDownMenu#8]
我将遇到的问题写在了这个工程里面，两个控制器一个是正确的形式，一个是错误的形式。想请教下这里的事件响应为什么会被父控件处理掉。谢谢。这是工程链接https://github.com/tangzzz-fan/testUseSDWebImage.git

**Comment by jsfu** [comment]
抱歉，好久没来github了
你说的事件响应是指滚动事件吧？你把menu加到sectionheader中了，然后所有显示的menu都是add到sectionheader上的，而sectionheader是tableview的一个组成，就相当于你在scrollview中添加了一个view，滚动事件仍然会响应。你可以对menu代码进行修改，比如把用于显示的view add到最顶层视图中。希望对你有所帮助
